### ISSUE TITLE
Usage of multiple config files

### ISSUE THREAD

**Issue by mkoromina** [jdblischak/snakemake-rules#1]
Hi @jdblischak ,

Quick enquiry about snakemake (smk) rules and scripts for which I'd appreciate your input. 
Do you know whether it'd be feasible to do this: Given a pipeline, which is designed to analyze multiple datasets (as wildcards), use also .tsv files with additional variables  (which are needed as params for smk rules) as config files? In other words, can we have multiple config files on snakemake? And if yes, do these have to be necessarily list on the very beginning of the snakemake file? Do also the variables of each one of these files have to be defined as wildcards? 

Happy to provide an example if anything is not clear.
Many thanks!

**Comment by jdblischak** [comment]
> can we have multiple config files on snakemake?

Yes. Here's an minimal example that loads fields from two different config files:

```
# config1.yaml
a: 1

# config2.yaml
b: 2

# Snakefile
configfile: "config1.yaml"
configfile: "config2.yaml"

print(config["a"])
print(config["b"])
```

> And if yes, do these have to be necessarily list on the very beginning of the snakemake file?

That would likely be advisable to keep things manageable. Though it would likely depend on the order of the rules and which values of the config file they depended on.

For your other questions, I would need a better sense of what you are trying to accomplish. With the flexibility of Snakemake, the answer to "can I do this?" is usually "yes". However, there are often easier ways to accomplish complex tasks.

**Comment by mkoromina** [comment]
Hi @jdblischak ,

Many thanks for sharing all these useful instructions!

What I am trying to accomplish is described as follows: use some  .tsv files produced from a snakemake rule, as my .config files for snakemake rules further down the pipeline. In other words, it is kinda tricky to define them at the very beginning of the pipeline, as they are produced based on a certain snakemake rule and then ideally, I'd like to use them as .config files. (Certain variables in them shall be parameters and criteria for running the subsequent snakemake rules).

Hope this helps and I am more than happy to listen to your feedback!
Many thanks!

**Comment by jdblischak** [comment]
Ah, ok. You need downstream rules to dynamically update based on the results of previous rules. Snakemake refers to this as [data-dependent conditional execution](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#data-dependent-conditional-execution). Essentially you can use a special `checkpoint` rule. My favorite example for this is a QC filtering step. A `checkpoint` rule allows you to apply QC rules so that only high quality samples are processed by the downstream rules.

Unfortunately these type of dynamic steps greatly increase the complexity of a Snakemake pipeline. I always have to re-skim the documentation whenever I need to write a `checkpoint` step. From a pragmatic standpoint, if the second half of your pipeline is so conditional on the first half, you might be better off simply separating them into distinct pipelines. Execute the first. Then execute the second using the output of the first. If your analysis is successful and colleagues want to run their data through your pipeline, then you could always return to this and try to engineer a solution to combine them into a single convenient pipeline.

**Comment by mkoromina** [comment]
Thanks so much for this!!
Truly appreciate your response and I think you are right: it may be better to run it this way (i.e., split into two distinct parts).

Many thanks once again!
